name: Release

on:
  push:
    branches: [main, develop]
    tags-ignore: ["**"]

jobs:
  health:
    name: Code Quality
    uses: cyrenity/tempo/.github/workflows/health-check.yml@main
  version:
    name: Create Version
    permissions: write-all
    needs: [health]
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.format.outputs.semver }}
      semver_tag: ${{ steps.semver-tag.outputs.semver_tag }}
      previous_tag: ${{ steps.semver-tag.outputs.previous_tag }}
      is_prerelease: ${{ steps.semver-tag.outputs.is_prerelease }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Calculate semver tag
        id: semver-tag
        uses: gandarez/semver-action@master
        with:
          branching_model: trunk-based
          main_branch_name: "main"
          prefix: "" 
          debug: true
      - name: Remove v prefix
        id: format
        run: |
          echo "${{ steps.semver-tag.outputs.semver_tag }}"
          ver=`echo "${{ steps.semver-tag.outputs.semver_tag }}" | sed 's/^v//'`
          echo "$ver"
          echo "semver=$ver" >> $GITHUB_OUTPUT
      - name: Create tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN || github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.format.outputs.semver }}",
              sha: context.sha
            })

  release:
    name: Release
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  build:
    name: Build
    uses: cyrenity/tempo/.github/workflows/build.yml@main
    with: 
      version: ${{ steps.format.outputs.semver }}


    
        
     # - name: "Create release"
     #   uses: "marvinpinto/action-automatic-releases@latest"
     #   with:
     #    repo_token: ${{ secrets.GH_TOKEN || github.token }}
     #    automatic_release_tag: ${{ needs.version.outputs.semver_tag }}
     #    prerelease: false

      - name: "Create release"
        uses: softprops/action-gh-release@master
        with:
          name: ${{ needs.version.outputs.semver }}
          tag_name: ${{ needs.version.outputs.semver }}
          prerelease: ${{ needs.version.outputs.is_prerelease }}
          generate_release_notes: true 
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Remove tag if failure
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN || github.token }}
          script: |
            github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/${{ needs.version.outputs.semver }}"
            })
